import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { useTheme } from "@/components/theme-provider";
import { ImageGenerator } from "../components/image-generator";
import { ImageGallery } from "../components/image-gallery";
import { LoadingAnimation } from "../components/loading-animation";
import { Sun, Moon, CheckCircle, Zap, Lock, Lightbulb } from "lucide-react";
import type { GeneratedImage } from "@shared/schema";

export default function Home() {
  const { theme, toggleTheme } = useTheme();
  const [latestImage, setLatestImage] = useState<GeneratedImage | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const { data: images = [], isLoading } = useQuery<GeneratedImage[]>({
    queryKey: ["/api/images"],
    refetchInterval: false,
  });

  return (
    <div className="min-h-screen">
      {/* Header */}
      <header className="relative z-10 p-6">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          {/* Logo */}
          <div className="flex items-center space-x-3">
            <div className="w-10 h-10 gradient-bg rounded-xl flex items-center justify-center shadow-lg">
              <CheckCircle className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-3xl font-bold gradient-text">Anvesh AI</h1>
          </div>
          
          {/* Theme Toggle */}
          <Button
            onClick={toggleTheme}
            variant="outline"
            size="icon"
            className="p-3 rounded-xl bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm border border-gray-200/50 dark:border-gray-700/50 hover:bg-white dark:hover:bg-slate-700 shadow-lg"
          >
            {theme === "dark" ? (
              <Sun className="w-5 h-5" />
            ) : (
              <Moon className="w-5 h-5" />
            )}
          </Button>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-6 pb-12">
        
        {/* Hero Section */}
        <section className="text-center mb-12">
          <h2 className="text-5xl md:text-6xl font-bold text-gray-900 dark:text-white mb-6 leading-tight">
            Create Amazing <span className="gradient-text">AI Art</span><br />
            <span className="text-3xl md:text-4xl font-medium text-gray-600 dark:text-gray-300">for Free</span>
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto mb-12">
            Generate unlimited high-quality images using state-of-the-art AI models. No signup required, completely free forever.
          </p>
        </section>

        {/* Image Generator */}
        <section className="mb-16">
          <ImageGenerator 
            onImageGenerated={setLatestImage}
            isGenerating={isGenerating}
            setIsGenerating={setIsGenerating}
          />
        </section>

        {/* Loading Animation */}
        {isGenerating && (
          <section className="mb-16">
            <LoadingAnimation />
          </section>
        )}

        {/* Latest Result */}
        {latestImage && !isGenerating && (
          <section className="mb-16">
            <div className="max-w-4xl mx-auto">
              <h3 className="text-3xl font-bold text-gray-900 dark:text-white mb-8 text-center">Your Latest Creation</h3>
              <Card className="bg-white/80 dark:bg-slate-800/80 backdrop-blur-sm shadow-xl border border-gray-200/50 dark:border-gray-700/50">
                <CardContent className="p-6">
                  <div className="relative group">
                    <img 
                      src={latestImage.imageUrl} 
                      alt="Generated AI image" 
                      className="w-full rounded-xl shadow-lg"
                    />
                    
                    {/* Watermark */}
                    <div className="absolute bottom-4 right-4 bg-black/70 text-white px-3 py-1 rounded-lg text-sm font-medium">
                      Generated by Anvesh AI
                    </div>
                    
                    {/* Download Button */}
                    <Button 
                      className="absolute top-4 right-4 opacity-0 group-hover:opacity-100 transition-all duration-200"
                      variant="secondary"
                      size="icon"
                      onClick={() => {
                        const link = document.createElement('a');
                        link.href = latestImage.imageUrl;
                        link.download = `anvesh-ai-${latestImage.id}.jpg`;
                        link.click();
                      }}
                    >
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                      </svg>
                    </Button>
                  </div>
                  
                  {/* Image Info */}
                  <div className="mt-6 flex items-center justify-between">
                    <div>
                      <p className="text-sm text-gray-500 dark:text-gray-400 mb-1">Prompt:</p>
                      <p className="text-gray-800 dark:text-gray-200 font-medium">{latestImage.prompt}</p>
                    </div>
                    <div className="flex space-x-3">
                      <Button 
                        variant="outline"
                        size="sm"
                        onClick={() => {
                          if (navigator.share) {
                            navigator.share({
                              title: 'Check out this AI-generated image!',
                              text: 'Created with Anvesh AI',
                              url: window.location.href
                            });
                          } else {
                            navigator.clipboard.writeText(window.location.href);
                          }
                        }}
                        className="bg-blue-100 dark:bg-blue-900 hover:bg-blue-200 dark:hover:bg-blue-800 text-blue-700 dark:text-blue-300"
                      >
                        <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z"/>
                        </svg>
                        Share
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </section>
        )}

        {/* Image History */}
        <section className="mb-16">
          <ImageGallery images={images} isLoading={isLoading} />
        </section>

        {/* Features Section */}
        <section className="mb-16">
          <div className="max-w-6xl mx-auto">
            <h3 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-12">Why Choose Anvesh AI?</h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {/* Feature 1 */}
              <div className="text-center">
                <div className="w-16 h-16 gradient-bg rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg">
                  <Zap className="w-8 h-8 text-white" />
                </div>
                <h4 className="text-xl font-bold text-gray-900 dark:text-white mb-3">Lightning Fast</h4>
                <p className="text-gray-600 dark:text-gray-300">Generate high-quality images in seconds with our optimized AI models</p>
              </div>
              
              {/* Feature 2 */}
              <div className="text-center">
                <div className="w-16 h-16 gradient-bg rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg">
                  <Lock className="w-8 h-8 text-white" />
                </div>
                <h4 className="text-xl font-bold text-gray-900 dark:text-white mb-3">Completely Free</h4>
                <p className="text-gray-600 dark:text-gray-300">No limits, no subscriptions, no hidden fees. Create unlimited images forever</p>
              </div>
              
              {/* Feature 3 */}
              <div className="text-center">
                <div className="w-16 h-16 gradient-bg rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg">
                  <Lightbulb className="w-8 h-8 text-white" />
                </div>
                <h4 className="text-xl font-bold text-gray-900 dark:text-white mb-3">No Sign-up Required</h4>
                <p className="text-gray-600 dark:text-gray-300">Start creating immediately without any account setup or personal information</p>
              </div>
            </div>
          </div>
        </section>

      </main>

      {/* Footer */}
      <footer className="bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm border-t border-gray-200/50 dark:border-gray-700/50 py-12">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center">
            <div className="flex items-center justify-center space-x-3 mb-6">
              <div className="w-8 h-8 gradient-bg rounded-lg flex items-center justify-center">
                <CheckCircle className="w-5 h-5 text-white" />
              </div>
              <span className="text-2xl font-bold gradient-text">Anvesh AI</span>
            </div>
            <p className="text-gray-600 dark:text-gray-300 mb-6 max-w-2xl mx-auto">
              Empowering creativity through artificial intelligence. Generate unlimited beautiful images with our free, open-source AI image generator.
            </p>
            <div className="flex items-center justify-center space-x-6 mb-8">
              <a href="#" className="text-gray-500 hover:text-purple-500 dark:text-gray-400 dark:hover:text-purple-400 transition-colors duration-200">
                Privacy Policy
              </a>
              <a href="#" className="text-gray-500 hover:text-purple-500 dark:text-gray-400 dark:hover:text-purple-400 transition-colors duration-200">
                Terms of Service
              </a>
              <a href="#" className="text-gray-500 hover:text-purple-500 dark:text-gray-400 dark:hover:text-purple-400 transition-colors duration-200">
                API Documentation
              </a>
              <a href="#" className="text-gray-500 hover:text-purple-500 dark:text-gray-400 dark:hover:text-purple-400 transition-colors duration-200">
                GitHub
              </a>
            </div>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              © 2024 Anvesh AI. Made with ❤️ for the creative community.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
